// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/san_collection/san_caches"
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"github.com/pdcgo/user_service"
	"github.com/urfave/cli/v3"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (*cli.Command, error) {
	serveMux := http.NewServeMux()
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	client := NewRedisDatabase(appConfig)
	cacheManager := san_caches.NewRedisCacheManager(client)
	registerHandler := user_service.NewRegister(serveMux, db, appConfig, defaultInterceptor, cacheManager)
	registerReflectFunc := custom_connect.NewRegisterReflect(serveMux)
	serviceApiFunc := NewServiceApiFunc(serveMux, registerHandler, registerReflectFunc)
	syncLegacyFunc := NewSyncLegacyFunc(db, appConfig)
	command := NewApp(serviceApiFunc, syncLegacyFunc)
	return command, nil
}
